# Generated by Django 5.2.1 on 2025-07-11 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='height',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='standarduser',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(700)]),
        ),
    ]
