# Generated by Django 5.2.1 on 2025-07-11 00:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_standarduser_height_alter_standarduser_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1906, 8, 21)), django.core.validators.MaxValueValidator(datetime.date(2007, 7, 12))]),
        ),
    ]
