# Generated by Django 5.2.1 on 2025-07-11 00:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('target_weight', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(700)])),
                ('target_bmi', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_achieved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'goal',
                'verbose_name_plural': 'goals',
                'ordering': ['user__username', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 10)), django.core.validators.MaxValueValidator(datetime.date(2025, 7, 11))])),
                ('calories_burned', models.DecimalField(decimal_places=1, default=0, help_text='Calories burned during the workout', max_digits=6, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'workout',
                'verbose_name_plural': 'workouts',
                'ordering': ['progress_sheet', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2025)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progress_sheet',
                'verbose_name_plural': 'progress_sheets',
                'order_with_respect_to': 'user',
                'unique_together': {('year', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fitness.workout')),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'ordering': ['workout'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='progress_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.progresssheet'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('goal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fitness.goal')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'order_with_respect_to': 'user',
            },
            bases=('fitness.goal',),
        ),
    ]
